//Orders
export const REQUEST_ORDERS = "REQUEST_ORDERS";
export const RECEIVE_ORDERS = "RECEIVE_ORDERS";
export const NOT_RECEIVE_ORDERS = "NOT_RECEIVE_ORDERS";
export const SELECT_ORDER = "SELECT_ORDER";
export const CHANGE_ORDER_ADDRESS = "CHANGE_ORDER_ADDRESS";
