name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: build and deploy on heroku
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build

      # Deploys on heroku
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "test-ils" 
          heroku_email: "kirill.ateev59@gmail.com"
