name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Setup...
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
     
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - name: Running tests
          shell: bash
          run: yarn test:unit
